### PR TITLE
Why relational databases don't handle big data well

### PR DESCRIPTION
**Pull request by kshin16**
@jtae0201 @haeinjeong @bkim4248 @ssangminlee 

Have any of you have first hand experience in handling big data? Any comment/feedback is much appreciated.

### CODE REVIEW

**Comment by ssangminlee** [comment]
Your contents looks great!
I believe your work will look much nicer if you consider some line breaks.

**Comment by bkim4248** [comment]
Great topic! keep working on it.

**Comment by kshin16** [comment]
How does this file look now?

**Comment by haeinjeong** [comment]
Looks great now! :+1: Let's :ship: it! :)

**Comment by ssangminlee** [comment]
Awesome Job!! :+1: :+1:  Must :ship: this one!!!

**Comment by jtae0201** [comment]
Looks great! :clap: :ship:!

**Comment by bkim4248** [comment]
Looks good! :+1: :ship: it!

**Pull request merged**
