### PR TITLE
Specifying software

### PR DESCRIPTION
**Pull request by bkim4248**
@ssangminlee
@haeinjeong 
@jtae0201 
@kshin16 

Feel free to be cruel on me.

### CODE REVIEW

**Comment by ssangminlee** [comment]
@bkim4248 Very nice and neat! I believe your work is ready to go :+1:
I recommend to :ship: this one!!

**Comment by kshin16** [comment]
Perfect let's :+1 :ship: this one!!

**Comment by haeinjeong** [comment]
Looks great :) :+1: Let's :ship:  this one!

**Comment by jtae0201** [comment]
:smiley::ship:it!

**Pull request merged**
