### PR TITLE
How to identify a good programmer

### PR DESCRIPTION
**Pull request by haeinjeong**
@ssangminlee This is my first draft

### CODE REVIEW

**Comment by ssangminlee** [comment]
@haeinjeong I reviewed your work, and it seems like you need to elaborate more.
Also, it would be great if you can find another photo.

**Comment by bkim4248** [comment]
@haeinjeong I think you found the key. Pay a lot! More explanation would be great.

**Comment by kshin16** [comment]
Money always talks !

**Comment by haeinjeong** [comment]
@ssangminlee @bkim4248 @kshin16 @jtae0201 Any feedback? :)

**Comment by ssangminlee** [comment]
Perfect!!  very insightful!! :+1: :+1:  :ship: it!! :ship: it !!!

**Comment by jtae0201** [comment]
Looks great.:smile::clap: :ship: it!! :ship: it !!!

**Comment by bkim4248** [comment]
Love it! :+1: :ship: it!

**Comment by kshin16** [comment]
@haeinjeong  Looks great! :+1: Let's :ship: it!

**Pull request merged**
